spring:
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: postgres


jwt:
  secret-key: fast_campus.sns-applicatoin-2024.secret_key
  #30days
  token.expired-time-ms: 2592000000


