spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/fast_sns
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver